create extension if not exists pgcrypto;

create table if not exists public.questions (
  id uuid primary key default gen_random_uuid(),
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('A', 'B', 'C', 'D')),
  explanation text,
  category text,
  difficulty text,
  created_at timestamp with time zone default now()
);

create unique index if not exists questions_seed_hash_idx
on public.questions ((md5(question_text || option_a || option_b || option_c || option_d)));

alter table public.questions enable row level security;

drop policy if exists "Authenticated users can read questions" on public.questions;
create policy "Authenticated users can read questions"
on public.questions for select to authenticated
using (true);

insert into public.questions (
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  category,
  difficulty
) values
  ('Niña de 4 años acude al centro de salud para control. Luego de la valoración antropométrica, se determina que el indicador peso para la talla se encuentra por debajo de −3 desviaciones estándar. ¿Qué problema de crecimiento presenta la niña?', 'Desnutrición aguda moderada', 'Desnutrición crónica o baja talla', 'Desnutrición aguda severa', 'Desnutrición crónica severa o baja talla severa', 'C', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS CAC'),
  ('El líder de enfermería del hospital realiza un plan de cuidado de enfermería en el cual se pone énfasis en valorar los diferentes factores que implican seguir un proceso de parto que requiere cesárea electiva en el embarazo. Se llega a varias conclusiones para brindar educación a los pacientes antes del último trimestre. ¿Cuál de las siguientes infecciones requiere una cesárea electiva durante el embarazo?', 'Herpes simple', 'VIH', 'Hepatitis', 'Hidrorrea de mas de 6 horas', 'A', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS CAC'),
  ('Recién nacido de 3 días de vida, con antecedentes de asfixia perinatal, presenta un paro cardiorrespiratorio. El equipo de salud inicia maniobras de reanimación. Tras 30 segundos de ventilación efectiva y compresiones torácicas, la frecuencia cardíaca continúa por debajo de 60 latidos por minuto.De acuerdo con las guías de reanimación neonatal, ¿cuál es el medicamento que debe prepararse para su administración inmediata?', 'Dexametasona.', 'Adrenalina.', 'Dopamina.', 'Aminofilina.', 'B', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS CAC'),
  ('Paciente en labor de parto es evaluada por el médico residente, quien durante la valoración realiza un tacto vaginal y determina un borramiento del 90 % y dilatación de 8 cm. Después de una hora, el médico tratante realiza un nuevo tacto vaginal para corroborar la valoración, pese a la resistencia de la paciente.¿A qué tipo de violencia corresponde esta situación?', 'Violencia psicológica.', 'Violencia física.', 'Violencia gineco-obstétrica.', 'Negligencia médica.', 'C', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS CAC'),
  ('Paciente de 52 años acude al centro de salud porque refiere sofocos frecuentes, insomnio y cambios de humor. Comenta que su última menstruación fue hace más de un año. No presenta antecedentes patológicos relevantes y no utiliza tratamiento hormonal. Expresa preocupación por su salud ósea, ya que su madre tuvo fractura de cadera por osteoporosis.De acuerdo con el caso, ¿cuál es la intervención de enfermería más adecuada?', 'Indicar que los síntomas son normales y que no requieren atención específica.', 'Educar sobre los cambios fisiológicos de la menopausia y promover hábitos saludables, como ejercicio y dieta rica en calcio y vitamina D.', 'Sugerir el uso de suplementos herbales sin necesidad de consulta médica.', 'Recomendar el inicio inmediato de terapia hormonal sustitutiva con estrógenos para aliviar los síntomas.', 'B', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS CAC'),
  ('Lactante de 17 meses acude al centro de salud acompañado de su madre, quien refiere que el niño no quiere lactar y permanece somnoliento. Además, presenta cuatro deposiciones líquidas en las últimas horas. Durante la valoración se evidencian ojos hundidos, mucosas orales secas y estado letárgico.¿Cuál es el estado de hidratación y la intervención de enfermería más adecuada en este caso?', 'Disentería grave. Iniciar solución salina a 90 mL/kg y canalizar vía periférica en el hospital.', 'Deshidratación grave. Aplicar Plan C y referir de urgencia al hospital.', 'Diarrea persistente. Iniciar vitamina A, administrar zinc por 14 días y explicar signos de alarma.', 'Deshidratación moderada. Aplicar Plan B con sales de rehidratación oral a 50 mL/kg.', 'B', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS CAC'),
  ('Primigesta de 35 años cursa el posparto inmediato. El recién nacido fue macrosómico, con peso de 4,26 kg. Como antecedentes presenta desprendimiento prematuro de placenta normoinserta y preeclampsia grave. Se administran oxitócicos prescritos y se realiza masaje uterino cada hora. A las dos horas del parto elimina aproximadamente 1200 mL de sangre, por lo que se activa la clave obstétrica roja.¿Cuál es la probable complicación puerperal que presenta la paciente?', 'Inversión uterina completa.', 'Hemorragia posparto tardía.', 'Rotura traumática uterina.', 'Hemorragia posparto.', 'D', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS CAC'),
  ('En la valoración de un paciente se evidencian ansiedad, confusión mental, palidez, piel fría y oliguria, manifestaciones características de un estado de shock agudo, definido como la incapacidad del sistema circulatorio para satisfacer las demandas metabólicas de oxígeno de los tejidos. ¿Qué tipo de shock se produce por la redistribución anormal de la sangre secundaria a vasodilatación periférica?', 'Shock hipovolémico.', 'Shock cardiogénico.', 'Shock distributivo.', 'Shock obstructivo.', 'C', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS CAC'),
  ('En la central de esterilización el personal de enfermería esta preparando el despacho del material para llevar a cabo una cirugía abdominopélvica lo cual requiere kit de ropa, equipos instrumentales de gran tamaño y peso, insumos de material blanco para ser usados en este proceso quirúrgico. Que modelo de paquete es ideal en este caso', 'Tipo sobre', 'Bolsas de papel', 'Tipo rollo', 'Tipo Rectangular', 'D', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'CACES actualizado'),
  ('Un paciente masculino de 45 años ingresa al servicio de emergencia en compañía de su familiar, al examen físico presenta disnea, tos, sibilancia y refiere opresión en el pecho, Menciona que ah sido diagnosticado con asma bronquial, y la actual crisis se desencadeno cuando estaba ayudando en una limpieza en el domicilio de un amigo. De acuerdo con el caso antes descrito, que teoría de enfermería esta relacionado', 'Teoría de adaptación', 'Teoría de autocuidado', 'Teoría del entorno', 'Teoría de confort', 'C', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado Familiar, Comunitario e Intercultural', 'CACES actualizado'),
  ('Paciente femenina de 28 años acude al servicio de ginecología, refiriendo dolor pélvico recurrente y sangrado de origen menstrual, durante la valoración medica se solicita la colaboración para preparación del paciente para la realización de una ecografía transvaginal, con el objetivo de evaluar las estructuras pélvicas internas. Cuál es la estructura que se espera visualizar', 'Trompas de Falopio', 'Meato urinario', 'Labios menores', 'Monte de venus', 'A', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'CACES actualizado'),
  ('Un profesional de enfermería a terminado de realizar el aseo de un paciente fallecido debido a un infarto agudo de miocardio por arritmias malignas, ha retirado los catéteres en los orificios naturales y a colocado el cuerpo en decúbito supino con leve elevación de la cabeza. Porque se coloca el cuerpo en esta posición', 'Para disminuir la lividez calaverica en el rostro', 'Para evitar el drenaje sanguíneo de la cara', 'Para impedir la aparición de la regides calaverica', 'Para el enfriamiento cadavérico', 'B', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'CACES actualizado'),
  ('Un paciente se encuentra en la unidad de cuidados intensivos tras una cirugía mayor, el paciente presenta secreciones oculares debido a la presencia de una conjuntivitis post quirúrgica. Usted como profesional de enfermería necesita realizar un cuidado adecuado de los ojos del paciente para promover una correcta higiene y confort. Cual de las siguientes opciones es la mas adecuada', 'Lavar los ojos del paciente con clorhexidina al 3%', 'Lavar los ojos del paciente con agua caliente', 'Lavar los ojos del paciente con agua tibia', 'Lavar los ojos del paciente con clorhexidina al 4%', 'C', 'Respuesta importada del banco CACES. La opción correcta estaba resaltada en el documento fuente.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'CACES actualizado'),
  ('Paciente con diabetes diagnosticada acude a consulta con glucosa de 200 mg/dL. ¿Cuál es la prioridad de enfermería?', 'Administrar insulina de acción rápida de inmediato.', 'Educar al paciente en su estilo de vida y autocuidado.', 'Suspender la alimentación hasta normalizar la glucosa.', 'Indicar reposo absoluto y vigilar solo la glucemia.', 'B', 'La prioridad de enfermería en un paciente con diabetes diagnosticada y una glucosa de 200 mg/dL, si no presenta signos de alarma, es reforzar la educación terapéutica para promover el autocuidado, la adherencia al tratamiento, la alimentación saludable, la actividad física y el control de factores de riesgo. La evidencia señala que la educación en diabetes mejora el entendimiento de la enfermedad, favorece mejores prácticas de autocuidado y ayuda al control diario, por lo que forma parte central del rol de enfermería', 'Enfermería - Cuidados del Adulto y Adulto Mayor', 'PREGUNTAS EHEP'),
  ('Un paciente debe administrarse insulina por vía subcutánea. ¿Cuál es el cuidado prioritario primordial de enfermería?', 'Aplicar la medicación de 10 a 15 grados.', 'Rotar el sitio de inyección.', 'Masajear la zona después de la aplicación.', 'Aplicar la insulina en el mismo sitio para mejorar la absorción.', 'B', 'La rotación del sitio de inyección es un cuidado prioritario porque previene la lipodistrofia, la lipohipertrofia y la alteración en la absorción de la insulina. Si el paciente aplica la insulina repetidamente en el mismo punto, puede presentar variaciones en el control glucémico y complicaciones en el tejido subcutáneo.', 'Enfermería - Bases Educativas, Administrativas, Investigativas y Epidemiológicas', 'PREGUNTAS EHEP'),
  ('Paciente que será preparado para una cirugía digestiva. Como parte de la preparación del tracto digestivo, se indica la colocación de un enema. ¿Qué volumen es el más adecuado para un adulto?', '100 mL', '150 mL', '200 mL', '750 mL', 'D', 'En el adulto, los enemas de limpieza o preparación intestinal suelen requerir volúmenes de gran cantidad, generalmente entre 500 y 1000 mL, para lograr una evacuación efectiva del intestino antes de un procedimiento quirúrgico o diagnóstico. Por eso, entre las opciones dadas, 750 mL es la respuesta correcta y la más coherente con la técnica descrita en enfermería.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('Paciente que vive en la región oriental presenta dolor muscular y articular y es diagnosticado con paludismo. ¿Cuál es el vector que transmite esta enfermedad?', 'Mosquito Aedes aegypti', 'Mosquito Culex', 'Mosquito hembra del género Anopheles', 'Mosca doméstica', 'C', 'El paludismo o malaria es una enfermedad parasitaria causada por Plasmodium y transmitida principalmente por la picadura de hembras infectadas del mosquito del género Anopheles. Este vector es el responsable de llevar el parásito de una persona a otra, por lo que es la opción correcta.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('Paciente con diabetes mellitus acude a consulta y solicita orientación sobre qué alimento puede consumir para prevenir complicaciones y mantener un mejor control de su enfermedad. ¿Cuál de los siguientes alimentos es la mejor opción?', 'Sandía.', 'Melón.', 'Frutos secos.', 'Carne roja seca.', 'C', 'Los frutos secos son una opción adecuada en pacientes con diabetes porque aportan grasas saludables, fibra y proteínas, lo que ayuda a mejorar la saciedad y puede contribuir a un mejor control glucémico y cardiovascular. Las guías nutricionales para diabetes recomiendan snacks saludables como nueces, almendras, pistachos y maní sin sal, preferiblemente en porciones controladas', 'Enfermería - Cuidados del Adulto y Adulto Mayor', 'PREGUNTAS EHEP'),
  ('Paciente con edema en miembros inferiores 3+++ y disnea. ¿Cuál es la acción prioritaria de enfermería?', 'Controlar ingresos y egresos.', 'Administrar diuréticos de asa.', 'Elevar únicamente los pies del paciente.', 'Registrar el peso al final del turno.', 'B', 'La disnea junto con edema marcado sugiere sobrecarga de volumen, por lo que la prioridad es disminuir la retención de líquidos con un diurético de asa, según la indicación médica. El control de ingresos y egresos es importante, pero es una medida de vigilancia y no la intervención más inmediata ante el compromiso respiratorio.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('En un hospital, el centro quirúrgico presenta brotes de infecciones. Tras un estudio ambiental, se observa que ciertas condiciones de temperatura y humedad favorecen la proliferación de microorganismos. ¿Cuál de las siguientes condiciones ambientales es la más propensa para el crecimiento de infecciones en el área quirúrgica?', '20 °C y 20% de humedad', '23 °C y 40% de humedad', '24 °C y 50% de humedad', '25 °C y 60% de humedad', 'D', 'La temperatura y la humedad elevadas favorecen la supervivencia y proliferación de microorganismos en el ambiente hospitalario. En un centro quirúrgico, el control ambiental es fundamental para disminuir el riesgo de infección. Entre las opciones dadas, 25 °C con 60% de humedad representa la condición más favorable para el crecimiento microbiano, por lo que es la respuesta correcta.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('Paciente que requiere transfusión sanguínea, pero aún no es posible administrarla porque se están realizando pruebas cruzadas. ¿Cuál es el expansor de volumen temporal más adecuado según la situación clínica?', 'Solución salina al 0,9%', 'Ringer lactato', 'Emacel', 'Glucosada al 5%', 'C', 'Emacel es un expansor plasmático utilizado de forma temporal para mantener el volumen intravascular mientras se completa el proceso previo a la transfusión. Su utilidad principal es sostener la volemia y la perfusión del paciente hasta que la sangre sea compatible y segura para administrar.', 'Enfermería - Bases Educativas, Administrativas, Investigativas y Epidemiológicas', 'PREGUNTAS EHEP'),
  ('Paciente hospitalizado en preparación prequirúrgica para una cirugía programada en 12 horas. Presenta glicemia de 70 mg/dL, nerviosismo y temor. ¿Cuál es la intervención prioritaria de enfermería?', 'Administrar medicamento hipoglucemiante.', 'Administrar líquidos parenterales.', 'Suspender la preparación quirúrgica.', 'Indicar reposo absoluto sin realizar ninguna acción.', 'B', 'La prioridad de enfermería es corregir o prevenir la hipoglucemia y mantener la estabilidad del paciente antes del procedimiento quirúrgico. En este contexto, la administración de líquidos parenterales ayuda a conservar el equilibrio metabólico e hidroelectrolítico mientras se continúa la valoración y preparación preoperatoria. Caso clínico Paciente masculino de 58 años, programado para colecistectomía laparoscópica electiva. Presenta antecedentes de hipertensión arterial controlada con enalapril y diabetes mellitus tipo 2 controlada con metformina. No refiere disnea, dolor torácico ni limitación funcional. En la valoración preanestésica se encuentra hemodinámicamente estable, consciente, orientado y sin signos de descompensación aguda.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('Paciente masculino de 58 años, programado para colecistectomía laparoscópica electiva. Presenta antecedentes de hipertensión arterial controlada con enalapril y diabetes mellitus tipo 2 controlada con metformina. No refiere disnea, dolor torácico ni limitación funcional. En la valoración preanestésica se encuentra hemodinámicamente estable, consciente, orientado y sin signos de descompensación aguda. ¿Cuál es la clasificación ASA más adecuada para este paciente?', 'ASA I', 'ASA II', 'ASA III', 'ASA IV', 'B', 'El paciente tiene enfermedades sistémicas leves a moderadas controladas, como hipertensión arterial y diabetes mellitus, pero sin compromiso funcional grave ni descompensación aguda. Por eso corresponde a ASA II. COMPONENTE 5', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('En una unidad de neonatología, se realiza una investigación cuantitativa durante 3 semanas en prematuros de bajo peso al nacer hospitalizados. A los neonatos de la sala A se les aplica 1 hora de musicoterapia clásica diariamente, mientras que a los neonatos de la sala B no se les aplica la intervención. ¿A qué diseño de investigación corresponde este estudio?', 'Diseño experimental', 'Diseño cuasi experimental', 'Diseño correlacional', 'Diseño descriptivo', 'B', 'Este estudio corresponde a un diseño cuasi experimental porque existe una intervención aplicada por la investigadora o investigador, que es la musicoterapia, y se compara con otro grupo que no recibe la intervención. Sin embargo, no se menciona asignación aleatoria de los recién nacidos a los grupos, lo cual es característico de los diseños cuasi experimentales. No es experimental puro porque en ese tipo de diseño los participantes se asignan al azar. Tampoco es correlacional, ya que no solo se observa asociación entre variables, sino que se manipula una intervención. Y no es descriptivo, porque no se limita a describir una situación, sino que busca evaluar el efecto de una acción.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS EHEP'),
  ('En la Zona 3 de Salud, los profesionales de enfermería se reúnen para analizar su situación laboral y reconocen una baja contribución al mejoramiento de las condiciones de salud y calidad de vida de la población. El líder de enfermería informa además que persiste un trabajo monótono, con escaso interés en la aplicación de guías prácticas para procedimientos asistenciales. Según la valoración sociodemográfica y académica del personal, la mayoría posee formación de grado; sin embargo, a varios profesionales se les dificulta aplicar el modelo de atención para resolver problemas prioritarios de salud. ¿Qué estrategia del sistema de salud vigente deben aplicar los líderes de enfermería para mejorar esta situación?', 'Incluir la atención primaria de salud renovada en el sistema de salud.', 'Incorporar salud mental, enfoque de derechos, enfoque de género y cuidados paliativos en la red pública de salud.', 'Fortalecer la investigación, formación y capacitación del talento humano.', 'Centralizar únicamente la atención hospitalaria especializada.', 'C', 'La situación descrita evidencia debilidades en la aplicación del modelo de atención, en el uso de guías prácticas y en el desempeño profesional para resolver problemas prioritarios. Por ello, la estrategia más adecuada es fortalecer la investigación, la formación continua y la capacitación del talento humano, ya que esto permite desarrollar competencias, mejorar la práctica asistencial y favorecer la calidad del cuidado de enfermería.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('En un estudio de investigación de enfermería sobre la percepción de calidad de vida en pacientes con enfermedades crónicas, ¿cuál de las siguientes opciones describe correctamente el alcance exploratorio de la investigación?', 'Comparar la calidad de vida de los pacientes con enfermedades crónicas antes de recibir tratamiento cíclico.', 'Identificar los factores que influyen en la calidad de vida del paciente con enfermedades crónicas.', 'Evaluar la efectividad de un programa de intervención sobre la calidad de vida en pacientes con enfermedades crónicas.', 'Establecer la relación entre la calidad de vida y el tratamiento en pacientes con enfermedades crónicas.', 'B', 'El alcance exploratorio se utiliza cuando el tema ha sido poco estudiado o cuando se busca acercarse al fenómeno para identificar variables, factores o aspectos relevantes sin profundizar todavía en relaciones causales o en la efectividad de una intervención.', 'Enfermería - Bases Educativas, Administrativas, Investigativas y Epidemiológicas', 'PREGUNTAS EHEP'),
  ('En el centro de salud donde usted labora como profesional de enfermería, se ha planificado la campaña de salud “Cómo cuidar tu corazón”. Cada integrante del equipo de salud tiene asignada una actividad específica. ¿Cuál de los siguientes roles corresponde al profesional de enfermería dentro de esta campaña?', 'Educar, brindar apoyo y reforzamiento a un grupo de riesgo.', 'Fomentar la salud y la prevención de enfermedades.', 'Realizar únicamente actividades informativas de tensión y erradicación.', 'Brindar asesoramiento individual exclusivamente.', 'A', 'El rol de enfermería en una campaña comunitaria de salud se centra principalmente en la educación, orientación, apoyo y refuerzo de conductas saludables, especialmente en grupos de riesgo. En una campaña como “Cómo cuidar tu corazón”, enfermería cumple una función activa en la promoción de la salud, prevención de enfermedades cardiovasculares y fortalecimiento del autocuidado. Aunque las opciones B y D también forman parte de la labor profesional, la opción A es la más completa y específica para el trabajo de enfermería en una campaña de prevención dirigida a población vulnerable.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('En una comunidad rural, los profesionales de salud y actores locales se reúnen para analizar el incumplimiento de estrategias y acciones prioritarias de educación y comunicación relacionadas con el uso inadecuado de químicos en la agricultura y la exposición prolongada a la radiación solar. Los datos muestran aumento de quemaduras en la piel, persistencia de envejecimiento prematuro y mayor referencia de lesiones precancerosas y cáncer de piel a la unidad de salud oncológica.¿Qué acción debe replantear la licenciada en enfermería dentro de los procesos educativos de promoción de la salud?', 'Elaborar lineamientos para desarrollar procesos de educación y comunicación.', 'Aplicar un enfoque de interculturalidad en las acciones educativas.', 'Preparar un método expositivo como experta dirigido exclusivamente a los actores sociales.', 'Disponer herramientas educativas y de comunicación.', 'B', 'El problema descrito ocurre en una comunidad rural con características sociales y culturales propias, por lo que la estrategia educativa más adecuada es el enfoque de interculturalidad. Este permite adaptar la promoción de la salud a la realidad de la población, respetando sus costumbres, lenguaje, contexto productivo y formas de comprensión de la enfermedad y la prevención.', 'Enfermería - Bases Educativas, Administrativas, Investigativas y Epidemiológicas', 'PREGUNTAS EHEP'),
  ('Un paciente masculino de 90 años es ingresado al servicio de clínica con diagnóstico médico de fibrilación auricular en tratamiento con warfarina. Durante la noche se levanta para ir al baño y se resbala, pero no sufre ningún daño. ¿Cómo se denomina este suceso relacionado con la seguridad del paciente?', 'Evento adverso', 'Cuasievento', 'Evento centinela', 'Complicación esperada', 'B', 'Se denomina cuasievento porque ocurrió una situación de riesgo que pudo haber provocado daño al paciente, pero finalmente no produjo lesión ni complicación. No corresponde a evento adverso porque este implica daño real al paciente. Tampoco es evento centinela, ya que este tipo de evento se asocia con daño grave, muerte o secuelas permanentes.', 'Enfermería - Cuidado y Procedimientos Clínicos de Enfermería', 'PREGUNTAS EHEP'),
  ('Un recién nacido masculino, obtenido por cesárea y con bajo peso al nacer, presenta a las 24 horas de vida coloración amarilla de la piel y de los ojos. El personal de enfermería vigila esta condición para reportarla oportunamente. ¿Cómo se denomina este estándar de calidad de atención de enfermería?', 'Cuidado de los bebés recién nacidos con un peso inferior a 1500 g.', 'Expediente clínico de enfermería del cuidado del recién nacido', 'Seguimiento del desarrollo del recién nacido con amenaza de hipervilirrubinemia.', 'Atención digna.', 'C', 'La descripción corresponde a un recién nacido con signos tempranos de ictericia neonatal, por lo que el personal de enfermería debe vigilar la evolución de la bilirrubina, identificar signos de alarma y reportar oportunamente la situación. Esto se relaciona con el estándar de seguimiento del desarrollo del recién nacido con amenaza de hipervilirrubinemia, porque implica detección precoz, vigilancia continua y prevención de complicaciones.', 'Enfermería - Cuidados de la Mujer, Recién Nacido, Niño y Adolescente', 'PREGUNTAS EHEP'),
  ('Un hombre de 20 años, sin antecedentes personales, ingresa por fiebre, mialgias y artralgias. Al examen físico se encuentra alerta, con signos vitales dentro de parámetros normales. Los familiares refieren que en su comunidad se han detectado casos de Zika. La enfermera activa el sistema de vigilancia epidemiológica basado en eventos. ¿Qué tipo de fuente de información se está utilizando en esta vigilancia?', 'Fuentes formales.', 'Fuentes informales.', 'Censos demográficos.', 'Fuentes nacionales.', 'B', 'En la vigilancia epidemiológica basada en eventos, las fuentes informales incluyen reportes de la comunidad, rumores, comentarios de familiares, medios de comunicación y notificaciones no estructuradas. En este caso, la información aportada por los familiares sobre casos de Zika en la comunidad constituye una fuente informal, porque no proviene de un registro oficial o sistema formal de notificación. Las fuentes formales corresponden a registros oficiales, historias clínicas, notificaciones obligatorias y reportes institucionales. Los censos demográficos no se usan como fuente inmediata de alerta epidemiológica.Las fuentes nacionales son categorías más amplias y no describen el origen específico de la información del caso.', 'Enfermería - Cuidado Familiar, Comunitario e Intercultural', 'PREGUNTAS EHEP')
on conflict do nothing;

notify pgrst, 'reload schema';
